Updated CloudOnce site/repo links
jizc/CloudOnce pull request #55
Opened 2022-06-22 18:16 UTC by dvdfu

Hey! I know CloudOnce isn't updated much anymore, but I still use it frequently and love it 😄 

I noticed some of the links on Google, and this repo, were outdated since the site moved to [cloudonce.github.io](https://cloudonce.github.io/)

Just thought I'd change the links in `README.md` and the plugin itself to keep things up to date.

2022-06-22 18:39 UTC, jizc requested changes
Thanks for the PR! Nice to hear you're still getting some use out of CloudOnce😃

I'd like just a couple small changes to the PR.

2022-06-22 18:39 UTC, jizc commented on README.md
> +* [Trollpants repositories](https://github.com/orgs/Trollpants/repositories)
I think I'd prefer this point to `https://github.com/Trollpants`, as that has a readme giving a better overview. The link text can be `Trollpants GitHub`.

2022-06-22 18:39 UTC, jizc commented on source/PluginDev/Assets/Extensions/CloudOnce/readme.txt
> +https://cloudonce.github.io/CloudOnce
This link is broken, it should be `https://cloudonce.github.io`

2022-06-22 19:10 UTC, dvdfu commented
Thanks for such a quick review!

2022-06-22 19:11 UTC, merged

2022-08-31 01:08 UTC, AllyAhAlyas commented
Please I need Help, CloudOnce was working perfectly but it's suddenly stopped,
I tried to remove and reimport the 2.7.5 package, but same also the Cloud once menu has vanished from the menu list in unity editor. 
Pleassssse help me ..

2022-08-31 10:56 UTC, jizc commented
@AllyAhAlyas This is not a place to ask for support. The plugin is provided 'as-is', with no direct support.

I suggest you try the [Unity Forum](https://forum.unity.com/) or [StackOverflow](https://stackoverflow.com/).